#!/bin/sh


        for opt in $(cat /proc/cmdline); do
                case "$opt" in
                console=*)
                        fulltty=${opt#console=}
                        tty=${fulltty%,*}
                        if [ -c "/dev/$tty" ] ; then
                                cat "setting up network stuff" >> "/dev/$tty"
                        fi
                esac
        done

echo "setting up network stuff..."
ip addr add 10.0.1.15/16 dev eth0
ip link set eth0 up
route add default gw 10.0.1.2
