#!/bin/sh

#  add a boot service to $sysroot
rc_add() {
	mkdir -p $sysroot/etc/runlevels/$2
	ln -sf /etc/init.d/$1 $sysroot/etc/runlevels/$2/$1
}

rc_add sshd default
rc_add dhcpcd default
rc_add urandom default
rc_add rngd default

chown -R root:root /root

# 9p-virtio
mkdir /port
mount -t 9p -o trans=virtio,version=9p2000.L port /port
mkdir /share
mount -t 9p -o trans=virtio share /share 

exec /sbin/init
